In [1]:

import platform
print("Python version is:",platform.python_version())


Python version is: 3.8.8


In [2]:
import numpy as np
print("Numpy version is:",np.__version__)
#press tab key so that we can access  the list of modules beautifully.

Numpy version is: 1.20.1


# Numpy Data types

In [3]:
import pandas as pd
dtypes = pd.DataFrame({'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']})
dtypes


Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

# Create a Numpy array with specified Data type

In [4]:
import numpy as np
arr=np.array([12.80,2,3,4.5],dtype='int')
print('Datatype of the array',arr,'is',arr.dtype)

Datatype of the array [12  2  3  4] is int32


In [5]:
arr=np.array([12.80,2,3,4.5],dtype="float")
print("Datatype of the array",arr,"is",arr.dtype)

Datatype of the array [12.8  2.   3.   4.5] is float64


In [6]:
arr=np.array([2+3j,6-8j],dtype='complex')
print("Datatype of the array ",arr,"is",arr.dtype)

Datatype of the array  [2.+3.j 6.-8.j] is complex128


In [7]:
arr=np.array([1,0,0,1,1],dtype='bool')
print("Datatype of the array is ",arr,"is",arr.dtype)

Datatype of the array is  [ True False False  True  True] is bool


### Set the max length of the string using S + some number, such as 'S3' any string longer than the max length will be truncated

In [8]:
s = np.array(['Chetan ' ,'salunke'], dtype='S3') #print size 3 ,elements of string if passed argument dtype=s3
print("The datatype of ", s ," is ",s.dtype)

The datatype of  [b'Che' b'sal']  is  |S3


In [9]:
s = np.array(['Chetan ' ,'salunke'], dtype='S7')
print("The datatype of ", s ," is ",s.dtype)

The datatype of  [b'Chetan ' b'salunke']  is  |S7


# Sequence Array

## Even values array 

In [10]:
 #np.arange(start,stop ,stepsize)
arr=np.arange(0,10,2)

In [11]:
print(arr)

[0 2 4 6 8]


# specified difference values array in  specified interval

In [12]:
# np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) 
arr = np.linspace(0,10, 5)
print(arr)


[ 0.   2.5  5.   7.5 10. ]


In [13]:
step=np.linspace(0,10,5,endpoint=False, retstep=True,dtype='int')
print("array:",arr)
print("step:",step)

array: [ 0.   2.5  5.   7.5 10. ]
step: (array([0, 2, 4, 6, 8]), 2.0)


In [14]:
arr, step = np.linspace(0, 10, 5, endpoint=False, retstep=True,dtype='int')
print("array: ",arr)
print("step :",step)

array:  [0 2 4 6 8]
step : 2.0


# Create An Array Of Random Values In A Given Shape

In [15]:
arr=np.random.rand(2,3)
print(arr)

[[0.91686492 0.56368849 0.74030073]
 [0.58119707 0.20763287 0.3544387 ]]


# Create an Array of Zeros in a Given Shape`

In [16]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


# Create An Array Of Zeros With The Same Shape And Data Type As A Given Array

In [17]:
arr

array([[0.91686492, 0.56368849, 0.74030073],
       [0.58119707, 0.20763287, 0.3544387 ]])

In [18]:
zeros=np.zeros_like(arr)
print(arr)  
print()
print(zeros)

[[0.91686492 0.56368849 0.74030073]
 [0.58119707 0.20763287 0.3544387 ]]

[[0. 0. 0.]
 [0. 0. 0.]]


# Create An Array Of Ones In A Given Shape

In [19]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
arr=np.random.rand(3,3)
arr

array([[0.82063103, 0.75936614, 0.41904554],
       [0.54970734, 0.26730007, 0.70368523],
       [0.02015736, 0.95756493, 0.8324204 ]])

In [21]:
ones=np.ones_like(arr)
print(arr)
print()
print(ones)

[[0.82063103 0.75936614 0.41904554]
 [0.54970734 0.26730007 0.70368523]
 [0.02015736 0.95756493 0.8324204 ]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Create an array of arbitrary values in a given shape

In [22]:
a=np.empty((2,2))
print(a)

[[ 2.5  5. ]
 [ 7.5 10. ]]


# Create an array of arbitrary values with the same shape and data type as a given array

In [23]:
a=np.ones((3,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
a=np.empty_like(a)
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


# Create an array of constant values in a given shape

In [25]:
arr=np.full((3,3),7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# Create an array of constant values with the same shape and data type as a given array

In [26]:
arr=np.full_like(arr,7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [27]:
print(np.full_like(arr,0))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
print(np.full_like(arr,1))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [29]:
a=np.random.rand(5,5)

In [30]:
row,col=a.shape
print(np.full_like(a,np.eye(row),dtype='int'))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# Create an array by repetition

### Repeat each element of an array(According to axis(row/col) by a specified number of times



###### here row 'or' col repeat at one time

In [31]:
arr=np.random.rand(2,2)
print(arr)

[[0.1407919  0.84479226]
 [0.71031599 0.6640668 ]]


In [32]:
arr=np.random.rand(2,2)
print("Original array:\n",arr)
print()
print("Repeated Element array:\n",np.repeat(arr, [5,1],axis=0))    # or np.repeat(range(3), 3)
#[5,1] first row repeat 5 times and second 1 time

type(arr)

Original array:
 [[0.43255416 0.17602959]
 [0.95649646 0.2229723 ]]

Repeated Element array:
 [[0.43255416 0.17602959]
 [0.43255416 0.17602959]
 [0.43255416 0.17602959]
 [0.43255416 0.17602959]
 [0.43255416 0.17602959]
 [0.95649646 0.2229723 ]]


numpy.ndarray

In [33]:
print("first col repeat 2 times and second col repeat 2 times\n")
np.repeat(arr,[2,2],axis=1) #[2,2] first col repeat 2 times and second col repeat 2 times.


first col repeat 2 times and second col repeat 2 times



array([[0.43255416, 0.43255416, 0.17602959, 0.17602959],
       [0.95649646, 0.95649646, 0.2229723 , 0.2229723 ]])

In [34]:
print("first row repeat 2 times and second row repeat 2 times\n")

np.repeat(arr,[2,2],axis=0)

first row repeat 2 times and second row repeat 2 times



array([[0.43255416, 0.17602959],
       [0.43255416, 0.17602959],
       [0.95649646, 0.2229723 ],
       [0.95649646, 0.2229723 ]])

## Repeat an array with specified number of times

##### here row 'and ' col repeat at one time

In [35]:
np.tile(arr,(1,2)) #np.tile(array,(a,b)) 

array([[0.43255416, 0.17602959, 0.43255416, 0.17602959],
       [0.95649646, 0.2229723 , 0.95649646, 0.2229723 ]])

In [36]:
np.tile(arr,(2,1))

array([[0.43255416, 0.17602959],
       [0.95649646, 0.2229723 ],
       [0.43255416, 0.17602959],
       [0.95649646, 0.2229723 ]])

In [37]:
np.tile(arr,(2,2))

array([[0.43255416, 0.17602959, 0.43255416, 0.17602959],
       [0.95649646, 0.2229723 , 0.95649646, 0.2229723 ],
       [0.43255416, 0.17602959, 0.43255416, 0.17602959],
       [0.95649646, 0.2229723 , 0.95649646, 0.2229723 ]])

# create an identity matrix with a given diagonal size

In [38]:
Identity=np.eye(3)

In [39]:
print(Identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
print(np.eye(3,dtype='int'))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [41]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Create an identity matrix with a diagonal offset


In [42]:
I=np.eye(5,k=1)   # positive number shifts the diagonal upward
print(I)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [43]:
print(np.eye(5,k=2))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [44]:
I=np.eye(5,k=-1)  # negative number shifts the diagonal downward
print(I)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


# Extract the diagonal array / create a diagonal array

In [45]:
arr=np.random.rand(2,2)
print(arr)

[[0.34650754 0.83096492]
 [0.64615272 0.00981097]]


In [46]:
np.diag(arr)  #Extract the diagonal elements of array

array([0.34650754, 0.00981097])

In [47]:
arr=np.diag([1,2,4])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 4]]


# Inspect Arrays

## Inspect general information of an array

In [48]:
arr=np.array([[2,3,5],[7,11,13]])

In [49]:
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x242e72cba10
byteorder:  little
byteswap:  False
type: int32
None


## Inspect the data type of an array

In [50]:
print(arr.dtype)

int32


## inspect the dimension of an array

In [51]:
row,col=arr.shape
print(row,col)

2 3


## Inspect length of an array

In [52]:
print(len(arr))

2


## Inspect the number of dimensions of an array

In [53]:
print(arr.ndim)

2


## Inspect the number of elements in an array

In [54]:
print(arr.size)

6


In [55]:
print(arr.itemsize)

4


## Inspect the memory size of an array (in byte)

In [56]:
# arr.nbytes = arr.size * arr.itemsize (total memory taken by array)
print(arr.nbytes)

24


# Sampling Methods

## Set seed

In [57]:
np.random.seed(123) #this fix the random numbers,if each coder user have same seed then each will get same random numbers generated

## Generate a random sample from interval [0, 1) in a given shape

In [58]:
print(np.random.rand()) #generated random number 

0.6964691855978616


In [59]:
print(np.random.rand(1,3)) #generate 1D array

[[0.28613933 0.22685145 0.55131477]]


In [60]:
print(np.random.rand(3,2)) #generate 2D array

[[0.71946897 0.42310646]
 [0.9807642  0.68482974]
 [0.4809319  0.39211752]]


## Generate a sample from the standard normal distribution (mean = 0, var = 1)

In [61]:
print(np.random.randn(3,3))


[[ 1.26593626 -0.8667404  -0.67888615]
 [-0.09470897  1.49138963 -0.638902  ]
 [-0.44398196 -0.43435128  2.20593008]]


## Generate an array of random integers in a given interval [low, high)

In [62]:
#np.random.randint(low,high,size,dtype)
arr=np.random.randint(1,10,30,dtype='i8')
print(arr)

[9 1 8 4 5 7 2 6 7 3 2 9 4 6 1 3 7 3 5 5 7 4 1 7 5 8 7 8 2 6]


## generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [63]:
np.random.seed(12)
print(np.random.sample(5))
print(np.random.random(5))
print(np.random.ranf(5))
print(np.random.random_sample(5))

[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
[0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]
[0.28382835 0.60608318 0.94422514 0.85273554 0.00225923]
[0.52122603 0.55203763 0.48537741 0.76813415 0.16071675]


# Sampling Discrete Distribution

### Generate a random sample from a given Discrete Distribution

In [64]:
#np.random.choice(iterable_or_int,size,replace=True,Weight=p)

In [65]:
print(np.random.choice(4,10,replace=True,p=[0.1,0.5,0.3,0.1]))

[2 0 1 1 1 2 1 2 1 2]


In [66]:
print(np.random.choice(range(1,48),2,replace=False))  #generating random number from the (1,48) SRSWOR


[32 17]


In [67]:
print(np.random.choice(range(1,48),replace=True))  #generating random number from the (1,48) SRSWR(Bydefault)

38


In [68]:
print(np.random.choice([1,8,0],10))

[1 1 8 8 0 1 0 8 1 8]


In [69]:
print(np.random.choice(['a','b','c'], 10))


['a' 'c' 'b' 'c' 'b' 'a' 'c' 'a' 'a' 'a']


# Sampling from Various Distributions

In [70]:
print(np.random.normal(loc=11,scale=2,size=10))

[10.17635175 11.16715865 13.34977789 13.8264866  14.86714163  9.76282176
 11.38463197 12.36665898  8.64609023  8.68663503]


In [71]:
print(np.random.gamma(1,2,10))

[0.68908817 6.31262023 1.04161166 5.85823516 3.89248823 2.33545962
 0.00658677 4.60724125 5.04808191 0.01185377]


In [72]:
print(np.random.binomial(5,0.5,10))

[3 2 3 3 3 2 1 3 4 2]


In [73]:
print(np.random.exponential(5,10))    

[ 1.18245896  2.36958263  2.57791134 10.82184757  1.12920056  2.71515022
  5.22004063  3.58354243  2.03107058  7.5360638 ]


In [74]:
print(np.random.geometric(0.3,10))

[1 1 2 5 1 1 8 1 3 1]


In [75]:
print(np.random.poisson(5,10))

[4 1 1 5 5 6 5 6 6 5]


In [76]:
print(np.random.uniform(low=10,high=20,size=10))

[17.74940215 11.05895152 19.05395867 15.87886485 19.88089758 14.28661357
 16.29849979 17.76281334 12.59817488 16.38913069]


# Sampling from the Standerd Distributions

In [77]:
np.random.standard_normal(10)

array([ 0.08463606,  1.2982271 ,  1.02259447, -2.49075849,  1.08484657,
        0.64033546, -0.81598523,  0.23736343,  1.12665435,  3.32034526])

In [78]:
np.random.standard_normal((3,3))

array([[-0.97969203, -0.83460635,  0.32646965],
       [-1.24495911,  0.47712462, -0.77988871],
       [ 0.425084  ,  0.81795101, -0.65616086]])

In [79]:
np.random.standard_exponential(10)

array([0.71952406, 0.42190585, 0.78878253, 1.15873413, 0.35623632,
       0.24252749, 1.55262662, 1.49543511, 0.04262148, 1.03700566])

In [80]:
np.random.standard_gamma(10)

5.71996715489205

In [81]:
np.random.standard_t(10)

-1.6961295137591665

# Shuffle an array in place

In [82]:
arr=np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [83]:
np.random.shuffle(arr)
print(arr)

[1 6 7 5 2 9 8 4 3 0]


# Generate a permutation of an array


In [84]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('A permutation of the array: ', np.random.permutation(arr))
print('The initial array: ', arr)

A permutation of the array:  [7 0 4 6 2 8 3 9 1 5]
The initial array:  [0 1 2 3 4 5 6 7 8 9]


In [85]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


# Math Functions


In [86]:
arr = np.random.randint(1,9,size=(3,3))
print(arr)

[[3 3 3]
 [7 1 4]
 [8 5 1]]


## element-wise operations

In [87]:
print(arr+5)

[[ 8  8  8]
 [12  6  9]
 [13 10  6]]


In [88]:
print(arr-5)

[[-2 -2 -2]
 [ 2 -4 -1]
 [ 3  0 -4]]


In [89]:
print(arr*5)

[[15 15 15]
 [35  5 20]
 [40 25  5]]


In [90]:
print(arr/5)

[[0.6 0.6 0.6]
 [1.4 0.2 0.8]
 [1.6 1.  0.2]]


In [91]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.add(arr1,arr2)
arr4=np.subtract(arr1,arr2)
arr5=np.multiply(arr1,arr2)
arr6=np.divide(arr1,arr2)
print("arr1 and arr2:\n",arr1,arr2)
print("mathematical operations on arr1 and arr2:\n",arr3,arr4,arr5,arr6)

arr1 and arr2:
 [1 2 3] [4 5 6]
mathematical operations on arr1 and arr2:
 [5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


## Element-wise Exponentiation

In [92]:
np.exp(arr1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## Element-wise Logorithm

In [93]:
arr

array([[3, 3, 3],
       [7, 1, 4],
       [8, 5, 1]])

In [94]:
print(np.log(arr)) #natural log

[[1.09861229 1.09861229 1.09861229]
 [1.94591015 0.         1.38629436]
 [2.07944154 1.60943791 0.        ]]


In [95]:
print(np.log2(arr)) #Base 2

[[1.5849625  1.5849625  1.5849625 ]
 [2.80735492 0.         2.        ]
 [3.         2.32192809 0.        ]]


In [96]:
print(np.log10(arr)) #Base 10

[[0.47712125 0.47712125 0.47712125]
 [0.84509804 0.         0.60205999]
 [0.90308999 0.69897    0.        ]]


## Element-wise square root

In [97]:
print(arr)
print(np.sqrt(arr))

[[3 3 3]
 [7 1 4]
 [8 5 1]]
[[1.73205081 1.73205081 1.73205081]
 [2.64575131 1.         2.        ]
 [2.82842712 2.23606798 1.        ]]


## Element-wise sine and cosine

In [98]:
print(np.sin(arr))

[[ 0.14112001  0.14112001  0.14112001]
 [ 0.6569866   0.84147098 -0.7568025 ]
 [ 0.98935825 -0.95892427  0.84147098]]


In [99]:
print(np.cos(arr))

[[-0.9899925  -0.9899925  -0.9899925 ]
 [ 0.75390225  0.54030231 -0.65364362]
 [-0.14550003  0.28366219  0.54030231]]


## Sum along a specified axis(Row-wise,col-wise)

In [100]:
print(arr)

[[3 3 3]
 [7 1 4]
 [8 5 1]]


In [101]:
print(np.sum(arr,axis=1)) #Row-wise

[ 9 12 14]


In [102]:
print(np.sum(arr,axis=0)) #Col-wise

[18  9  8]


## Compute the min and max along a specified axis

In [103]:
arr

array([[3, 3, 3],
       [7, 1, 4],
       [8, 5, 1]])

In [104]:
# calculate min along the row
print(np.min(arr, axis=0))

[3 1 1]


In [105]:
# calculate max along the column
print(np.max(arr, axis=1))    

[3 7 8]


In [106]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

8
1


## Indices of the min and max along a specified axis


In [107]:
#gives the indices order according increasing order along axis
arr=np.random.rand(2,3)

In [108]:
print(arr)

[[0.99715933 0.31350396 0.56928356]
 [0.51747251 0.34883397 0.37380862]]


In [109]:
print(np.argmin(arr,axis=0)) #Index of Column Minimum
print(np.argmax(arr,axis=0)) #Index of Column Maximum

[1 0 1]
[0 1 0]


In [110]:
print(np.argmin(arr,axis=1)) #Index of Row Min
print(np.argmax(arr,axis=1)) #Index of Row Max

[1 1]
[0 0]


In [111]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

1
0


## Element-wise min and max of two arrays

In [112]:
arr1=np.array([1,2,3,6])
arr2=np.array([2,3,1,4])
print(np.maximum(arr1,arr2))
print(np.minimum(arr1,arr2))

[2 3 3 6]
[1 2 1 4]


## Split fractional and integral parts of a floating-point array

In [113]:
arr=np.random.rand(5)*1000

In [114]:
fractional,Integral=np.modf(arr)

In [115]:
print("Original Array: ",arr)
print("Fractional Part: ",fractional)
print("Integral Part: ",Integral)

Original Array:  [704.96178026 489.30815144 358.46428738 269.85632052 987.28679227]
Fractional Part:  [0.96178026 0.30815144 0.46428738 0.85632052 0.28679227]
Integral Part:  [704. 489. 358. 269. 987.]


## Mean Of the array

In [116]:
print(np.mean(arr))

561.9754663752276


In [117]:
arr=np.random.rand(2,3)
print(arr)

[[0.11000377 0.50936257 0.7326304 ]
 [0.14442983 0.43338355 0.2723895 ]]


In [118]:
#Mean along the row
print(np.mean(arr,axis=1))

[0.45066558 0.28340096]


In [119]:
(arr[0,0]+arr[0,1]+arr[0,2])/3

0.4506655811573433

In [120]:
#Mean along column
print(np.mean(arr,axis=0))

[0.1272168  0.47137306 0.50250995]


In [121]:
(arr[0,0]+arr[1,0])/2

0.12721680149840092

# Median

In [122]:
a=np.array([1,2,3,4,4])
print(np.median(a))

3.0


In [123]:
# compute the median along the row
print(np.median(arr,axis=0))

[0.1272168  0.47137306 0.50250995]


In [124]:
# compute the median along the column
print(np.median(arr,axis=1))

[0.50936257 0.2723895 ]


# Compute the percentile

In [125]:
arr=np.array([1,1,2,3,4,4,4,5,3,6,8,9])
print(np.quantile(arr,0.5))

4.0


$ x^{2}+2{x}+5 $

In [130]:
# compute 5, 65, and 95 percentiles of the array
l0=[5,65,95]
l=np.percentile(arr,[5,65,95])
for i in range(len(l)):
    print("%d th percentile is: %1.3f"%(l0[i],l[i]))

5 th percentile is: 1.000
65 th percentile is: 4.150
95 th percentile is: 8.450


# Compute the standard deviation & variance

In [164]:
# compute the overall standard deviation
print(np.std(arr))

0.8748897637790901


In [165]:
# compute the standard deviation along the row
print(np.std(arr,axis=0))

[0.47140452 0.         0.47140452]


In [166]:
arr=np.random.randint(1,5,(3,3))
print(arr)

[[3 2 2]
 [3 4 1]
 [2 1 1]]


In [167]:
#compute the standard deviation along the col
print((np.std(arr,axis=1)))


[0.47140452 1.24721913 0.47140452]


In [168]:
#compute the overall varience
print(np.var(arr))

0.9876543209876544


In [169]:
#compute the row varience
print(np.var(arr,axis=0))

[0.22222222 1.55555556 0.22222222]


In [170]:
#compute the col varience
print(np.var(arr,axis=1))

[0.22222222 1.55555556 0.22222222]


# Compute the covariance & correlation

In [171]:
print(np.cov(arr)) #varience covarience matrix

[[0.33333333 0.16666667 0.33333333]
 [0.16666667 2.33333333 0.16666667]
 [0.33333333 0.16666667 0.33333333]]


In [172]:
print(np.corrcoef(arr[:,0],arr[:,1]))

[[1.         0.75592895]
 [0.75592895 1.        ]]


# Compute cumulative sum & product

In [178]:
# calculate the cumulative sums along the row
print(np.cumsum(arr,axis=0))

[[3 2 2]
 [6 6 3]
 [8 7 4]]


In [179]:
#calculate the cumlative sumns along the col
print(np.cumsum(arr,axis=1))

[[3 5 7]
 [3 7 8]
 [2 3 4]]


In [180]:
#calculate the cumulative product along the row
print(np.cumsum(arr,axis=0))

[[3 2 2]
 [6 6 3]
 [8 7 4]]


# Element-wise comparison

In [184]:
arr1=np.array([1,5,2])
arr2=np.array([4,1,5])

In [185]:
#return an array of bools
print(arr1==arr2)

[False False False]


In [187]:
print(arr1<5)

[ True False  True]


# Slicing & Indexing

In [188]:
import numpy as np

In [192]:
arr=np.array(range(1,13)).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Select an element by row and column indices

In [193]:
print(arr)
print(arr[1][2])
# or more concisely
print(arr[2,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
11


In [195]:
print(arr)
print(arr[1:,1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7  8]
 [10 11 12]]


In [223]:
#ellipsis slicing: auto-complete the dimensions
arr=np.array(range(16)).reshape(2,2,2,2)
print(arr)
# equivalent to arr[0,:,:,:]
print(arr[1,...])

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


# Assign a scalar to a slice by broadcasting

In [225]:
print("Original Array:\n",arr)
arr[1:3,:]=100 # or simply arr[1:3]
print("New array:\n",arr)

Original Array:
 [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
New array:
 [[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


# Boolean Indexing

In [226]:
arr1=np.arange(25).reshape(5,5)

In [227]:
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [229]:
list1=[True,False,True,False,True]
arr1[list1] #print only those rows whos corresponding list elements are True

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [231]:
list2=np.array(['M','F',"M","M","F"])
print(arr1[list2=="M"])

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [232]:
# negate the condition
print(arr1[~(list2=="M")])
#print(arr1[~bools])  

[[ 5  6  7  8  9]
 [20 21 22 23 24]]


# Fancy Indexing

In [234]:
arr = np.random.rand(10,5)
arr

array([[0.08086612, 0.42139425, 0.37815804, 0.55535353, 0.37273794],
       [0.62000401, 0.18617024, 0.23032707, 0.94960083, 0.4897838 ],
       [0.66956398, 0.09664952, 0.54798152, 0.87213333, 0.10684084],
       [0.69369773, 0.31894294, 0.58486889, 0.46460341, 0.63021157],
       [0.91585374, 0.85874212, 0.45994221, 0.31573416, 0.78451334],
       [0.71090889, 0.47896126, 0.26478509, 0.10161119, 0.58254522],
       [0.02136428, 0.13414539, 0.84416081, 0.01509614, 0.44481843],
       [0.34552824, 0.12147171, 0.04877384, 0.55445967, 0.46205037],
       [0.56900672, 0.37214819, 0.86241016, 0.88056376, 0.52921303],
       [0.6863547 , 0.91255013, 0.39467652, 0.84435059, 0.34973782]])

In [236]:
print(arr[[1,2,3],[1,2,4]]) #Or arr[1,1],arr[2,2],arr[3,4]

[0.18617024 0.54798152 0.63021157]


In [237]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [4,2,3]]) 

[[0.63021157 0.58486889 0.46460341]
 [0.4897838  0.23032707 0.94960083]
 [0.10684084 0.54798152 0.87213333]]


In [248]:
arr=np.random.randint(range(1,10)).reshape(3,3)

In [249]:
print(arr)

[[0 0 1]
 [3 1 1]
 [1 4 0]]


In [254]:
arr[[0,2]][:,[0,2]]

array([[0, 1],
       [1, 0]])

# Dimension inference

In [262]:
# dimension inference using any negative number (usually -1)
arr=np.array(range(16)).reshape(4,-1)


In [263]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
